on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: anrchcontainerregistry.azurecr.io
        username: ${{ secrets.acr_anrchcontainerregistry_username }}
        password: ${{ secrets.acr_anrchcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t anrchcontainerregistry.azurecr.io/anrchclusterprisma:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push anrchcontainerregistry.azurecr.io/anrchclusterprisma:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_anrchclusterprisma_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep anrch_cluster_prismaad2e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace anrch_cluster_prismaad2e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: anrch_cluster_prismaad2e
        container-registry-url: anrchcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_anrchcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_anrchcontainerregistry_password }}
        secret-name: anrchclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: anrch_cluster_prismaad2e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          anrchcontainerregistry.azurecr.io/anrchclusterprisma:${{ github.sha }}
        imagepullsecrets: |
          anrchclusterdockerauth
